# Generated by Django 4.1.7 on 2023-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_uploaded', models.BooleanField(blank=True, default=False, null=True)),
                ('s3_url', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_share', models.IntegerField(default=0)),
                ('twitter_share', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
